version: "3"

services:

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PASS: sea-lutt # DONT DO THIS IN PROD -- acceptable in dev,
                    # but docker secrets should be used in prod
                    # in conjunction with docker swarm in place
                    # of docker compose
    ports:
      - 5000:5000
    volumes:
      - ./app:/app

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sea-lutt # DONT DO THIS IN PROD -- acceptable in dev,
                              # but docker secrets should be used in prod
                              # in conjunction with docker swarm in place
                              # of docker compose
